-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.


DROP TABLE IF EXISTS FBRP;
DROP TABLE IF EXISTS HISTORY;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS STRP;
DROP TABLE IF EXISTS CSRP;
DROP TABLE IF EXISTS CSBOARD;
DROP TABLE IF EXISTS STRUMF;
DROP TABLE IF EXISTS STRUMN;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS FREEBOARD;

-- ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- FreeBoard Table Create SQL
CREATE TABLE FREEBOARD
(
    `FBID`     INT              NOT NULL    AUTO_INCREMENT, 
    `FBTITLE`  VARCHAR(30)      NOT NULL, 
    `FBCONT`   VARCHAR(3000)    NOT NULL, 
    `FBDATE`   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP, 
    `FBCOUNT`  INT              DEFAULT 0,
    `FBREC`    INT              DEFAULT 0, 
    `FBIP`     VARCHAR(30)      NOT NULL, 
    `MEMID`    VARCHAR(15)      NOT NULL, 
    `BOARDID`  INT              NOT NULL, 
    PRIMARY KEY (FBID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- MEMBER Table Create SQL
CREATE TABLE MEMBER
(
    `MEMID`     VARCHAR(15)    NOT NULL, 
    `MEMPW`     VARCHAR(15)    NOT NULL, 
    `MEMNAME`   VARCHAR(15)    NOT NULL, 
    `MEMNICK`   VARCHAR(15)    NOT NULL, 
    `MEMEMAIL`  VARCHAR(30)    NOT NULL, 
    `MEMPHONE`  VARCHAR(13)    NULL, 
    `MEMADDR`   VARCHAR(50)    NULL, 
    `MEMAUTH`   INT            DEFAULT 5, 
    `MEMDATE`   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP, 
    `MEMLVL`    INT            DEFAULT 1, 
    PRIMARY KEY (MEMID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- BOARD Table Create SQL
CREATE TABLE BOARD
(
    `BOARDID`     INT            NOT NULL    AUTO_INCREMENT, 
    `BOARDTITLE`  VARCHAR(30)    NOT NULL, 
    PRIMARY KEY (BOARDID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- STRUMN Table Create SQL
CREATE TABLE STRUMN
(
    `STRID`     INT              NOT NULL    AUTO_INCREMENT, 
    `STRTITLE`  VARCHAR(30)      NOT NULL, 
    `STRCONT`   VARCHAR(3000)    NOT NULL, 
    `STRTYPE`   VARCHAR(15)      NOT NULL, 
    `STRIP`     VARCHAR(30)      NOT NULL, 
    `STRCOUNT`  INT              DEFAULT 0, 
    `STRDATE`   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP, 
    `BOARDID`   INT              NOT NULL, 
    `MEMID`     VARCHAR(45)      NOT NULL, 
    PRIMARY KEY (STRID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE STRUMN ADD CONSTRAINT FK_STRUMN_BOARDID_BOARD_BOARDID FOREIGN KEY (BOARDID)
 REFERENCES BOARD (BOARDID)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- STRUMF Table Create SQL
CREATE TABLE STRUMF
(
    `MAPID`     INT            NOT NULL    AUTO_INCREMENT, 
    `MAPNAME`   VARCHAR(50)    NOT NULL, 
    `MAPCOUNT`  INT            DEFAULT 0, 
    `MAPLOD`    VARCHAR(15)    NOT NULL, 
    `MAPTIME`   VARCHAR(15)    NOT NULL, 
    `MAPMINN`   INT            NOT NULL, 
    `MAPMAXN`   INT            NOT NULL, 
    `MAPVER`    VARCHAR(15)    NOT NULL, 
    `MAPCRT`    VARCHAR(20)    NULL, 
    `MAPMANA`   VARCHAR(1)     NOT NULL, 
    `STRID`     INT            NOT NULL, 
    PRIMARY KEY (MAPID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE STRUMF ADD CONSTRAINT FK_STRUMF_STRID_STRUMN_STRID FOREIGN KEY (STRID)
 REFERENCES STRUMN (STRID)  ON DELETE CASCADE ON UPDATE RESTRICT;


-- CSBOARD Table Create SQL
CREATE TABLE CSBOARD
(
    `CSID`     INT            NOT NULL    AUTO_INCREMENT, 
    `CSTYPE`   INT            NOT NULL, 
    `CSTITLE`  VARCHAR(30)    NOT NULL, 
    `CSCONT`   VARCHAR(3000)  NOT NULL, 
    `CSIP`     VARCHAR(30)    NOT NULL, 
    `CSDATE`   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP, 
    `CSFILE`   VARCHAR(30)    NULL, 
    `BOARDID`  INT            NOT NULL, 
    `MEMID`    VARCHAR(15)    NOT NULL, 
    PRIMARY KEY (CSID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CSBOARD ADD CONSTRAINT FK_CSBOARD_BOARDID_BOARD_BOARDID FOREIGN KEY (BOARDID)
 REFERENCES BOARD (BOARDID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSBOARD ADD CONSTRAINT FK_CSBOARD_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- CSRP Table Create SQL
CREATE TABLE CSRP
(
    `CSRPID`    INT             NOT NULL    AUTO_INCREMENT, 
    `CSRPCONT`  VARCHAR(300)    NOT NULL, 
    `CSRPDATE`  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP, 
    `CSID`      INT             NOT NULL, 
    `MEMID`     VARCHAR(15)     NOT NULL, 
    PRIMARY KEY (CSRPID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CSRP ADD CONSTRAINT FK_CSRP_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CSRP ADD CONSTRAINT FK_CSRP_CSID_CSBOARD_CSID FOREIGN KEY (CSID)
 REFERENCES CSBOARD (CSID)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- STRP Table Create SQL
CREATE TABLE STRP
(
    `STRPID`    INT             NOT NULL    AUTO_INCREMENT, 
    `STRPCONT`  VARCHAR(300)    NOT NULL, 
    `STRPREF`   INT             NOT NULL, 
    `STRPLVL`   INT             NOT NULL, 
    `STRPSTEP`  INT             NOT NULL, 
    `STRPDATE`  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP, 
    `STRPREC`   INT             DEFAULT 0, 
    `STRPREJ`   INT             DEFAULT 0, 
    `STRID`     INT             NOT NULL, 
    `MEMID`     VARCHAR(15)     NOT NULL, 
    PRIMARY KEY (STRPID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE STRP ADD CONSTRAINT FK_STRP_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE STRP ADD CONSTRAINT FK_STRP_STRID_STRUMN_STRID FOREIGN KEY (STRID)
 REFERENCES STRUMN (STRID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

 
-- CART Table Create SQL
CREATE TABLE CART
(
    `CARTID`  INT            NOT NULL    AUTO_INCREMENT, 
    `MAPID`   INT            NOT NULL, 
    `MEMID`   VARCHAR(15)    NOT NULL, 
    PRIMARY KEY (CARTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE CART ADD CONSTRAINT FK_CART_MAPID_STRUMF_MAPID FOREIGN KEY (MAPID)
 REFERENCES STRUMF (MAPID)  ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE CART ADD CONSTRAINT FK_CART_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE CASCADE ON UPDATE RESTRICT;


-- HISTORY Table Create SQL
CREATE TABLE HISTORY
(
    `HISTORYID`  INT            NOT NULL    AUTO_INCREMENT, 
    `HISDATE`    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP, 
    `MAPID`      INT            NOT NULL, 
    `MEMID`      VARCHAR(15)    NOT NULL, 
    PRIMARY KEY (HISTORYID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE HISTORY ADD CONSTRAINT FK_HISTORY_MAPID_STRUMF_MAPID FOREIGN KEY (MAPID)
 REFERENCES STRUMF (MAPID)  ON DELETE CASCADE ON UPDATE RESTRICT;

ALTER TABLE HISTORY ADD CONSTRAINT FK_HISTORY_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE CASCADE ON UPDATE RESTRICT;


-- FBRP Table Create SQL
CREATE TABLE FBRP
(
    `FBRPID`    INT             NOT NULL    AUTO_INCREMENT, 
    `FBRPREF`   INT             NOT NULL, 
    `FBRPLVL`   INT             NOT NULL, 
    `FBRPSTEP`  INT             NOT NULL, 
    `FBRPCONT`  VARCHAR(300)    NOT NULL, 
    `FBRPDATE`  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP, 
    `FBRPREC`   INT             DEFAULT 0, 
    `FBRPREJ`   INT             DEFAULT 0, 
    `FBID`      INT             NOT NULL, 
    `MEMID`     VARCHAR(15)     NOT NULL, 
    PRIMARY KEY (FBRPID)
);

ALTER TABLE FBRP ADD CONSTRAINT FK_FBRP_FBID_FREEBOARD_FBID FOREIGN KEY (FBID)
 REFERENCES FREEBOARD (FBID)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FBRP ADD CONSTRAINT FK_FBRP_MEMID_MEMBER_MEMID FOREIGN KEY (MEMID)
 REFERENCES MEMBER (MEMID)  ON DELETE RESTRICT ON UPDATE RESTRICT;
