	SELECT N.STRID AS N_STRID, 
		   N.STRTITLE AS N_STRTITLE,
		   N.STRCONT AS N_STRCONT,
		   N.STRTYPE AS N_STRTYPE,
		   N.STRCOUNT AS N_STRCOUNT,
		   F.MAPID AS F_MAPID,
		   F.MAPNAME AS F_MAPNAME,
		   F.MAPCOUNT AS F_MAPCOUNT,
		   F.MAPLOD AS F_MAPLOD,
		   F.MAPTIME AS F_MAPTIME,
		   F.MAPMINN AS F_MAPMINN,
		   F.MAPMAXN AS F_MAPMAXN,
		   F.MAPVER AS F_MAPVER,
		   F.MAPCRT AS F_MAPCRT,
		   F.MAPMANA AS F_MAPMANA,
		   F.STRID AS F_STRID
	  FROM STRUMN N LEFT JOIN STRUMF F
	    ON N.STRID = F.STRID